/* eslint-disable react-hooks/rules-of-hooks */
import { vibe3DCode } from '@/lib/vibe3DCode'
import { useObjectStore, useTabStore } from '@/store/appStore'
import {
  BaseBoxShapeUtil,
  DefaultSpinner,
  HTMLContainer,
  Icon,
  SvgExportContext,
  TLBaseShape,
  TLShape,
  toDomPrecision,
  useIsEditing,
  useToasts,
} from '@tldraw/tldraw'
import { useState, useEffect } from 'react'

export type Model3DPreviewShape = TLBaseShape<
  'model3d',
  {
    threeJsCode: string
    objectCode: string
    gltfUrl: string
    isGltf: boolean
    w: number
    h: number
    selectedShapes: TLShape[]
    objectId?: string
  }
>

export class Model3DPreviewShapeUtil extends BaseBoxShapeUtil<Model3DPreviewShape> {
  static override type = 'model3d' as const

  getDefaultProps(): Model3DPreviewShape['props'] {
    return {
      threeJsCode: '',
      objectCode: '',
      gltfUrl: '',
      isGltf: false,
      w: (960 * 2) / 3,
      h: (540 * 2) / 3,
      selectedShapes: [],
      objectId: '',
    }
  }

  override canEdit = () => true
  override isAspectRatioLocked = () => false
  override canResize = () => true
  override canBind = () => false
  override canUnmount = () => false

  onBeforeDelete = (shape: Model3DPreviewShape) => {
    try {
      const objectStore = useObjectStore.getState();
      const map = (window as any).__shapeToObjectMap;
      const mappedId = map ? map.get(shape.id) : null;
      const targetObj = objectStore.objects.find(
        o => o.id === shape.props.objectId || o.id === mappedId || (o as any).uuid === mappedId || o.userData?.tldrawShapeId === shape.id
      );
      if (targetObj) {
        console.log("Removing 3D object because 2D shape was deleted:", targetObj.id);
        objectStore.removeObject(targetObj.id);
      } else if (shape.props.objectId) {
        objectStore.removeObject(shape.props.objectId);
      } else if (mappedId) {
        objectStore.removeObject(mappedId);
      }
      if (map) {
        map.delete(shape.id);
      }
    } catch (err) {
      console.error("Error cleaning up 3D object on shape delete:", err);
    }
  }

  override component(shape: Model3DPreviewShape) {
    const isEditing = useIsEditing(shape.id)
    const toast = useToasts()
    const { addObjectFromCode, addObjectWithGltf } = useObjectStore()
    const { activeTab, setActiveTab } = useTabStore()
    const [isRegenerating, setIsRegenerating] = useState(false)
    const [isEditingModel, setIsEditingModel] = useState(false)

    // Listen for custom editing state change events
    useEffect(() => {
      const handleEditingStateChange = (event: Event) => {
        const customEvent = event as CustomEvent;
        if (customEvent.detail && customEvent.detail.elementId === shape.id) {
          setIsEditingModel(customEvent.detail.isEditing);
        }
      };

      window.addEventListener('model3d-editing-state-change', handleEditingStateChange);

      return () => {
        window.removeEventListener('model3d-editing-state-change', handleEditingStateChange);
      };
    }, [shape.id]);

    // Clean up 3D object when 2D shape is deleted from the canvas
    useEffect(() => {
      return () => {
        setTimeout(() => {
          try {
            const editor = (window as any).__tldraw_editor;
            // If the shape is no longer present in the tldraw store, it was deleted!
            if (editor && !editor.getShape(shape.id)) {
              console.log("2D shape was deleted from canvas, cleaning up 3D object:", shape.id);
              const objectStore = useObjectStore.getState();
              const map = (window as any).__shapeToObjectMap;
              const mappedId = map ? map.get(shape.id) : null;
              const targetObj = objectStore.objects.find(
                o => o.id === shape.props.objectId || o.id === mappedId || (o as any).uuid === mappedId || o.userData?.tldrawShapeId === shape.id
              );
              if (targetObj) {
                objectStore.removeObject(targetObj.id);
              } else if (shape.props.objectId) {
                objectStore.removeObject(shape.props.objectId);
              } else if (mappedId) {
                objectStore.removeObject(mappedId);
              }
              if (map) map.delete(shape.id);
            }
          } catch (err) {
            console.warn("Error during shape unmount cleanup:", err);
          }
        }, 50);
      };
    }, [shape.id, shape.props.objectId]);

    const rawCode = shape.props.threeJsCode ? shape.props.threeJsCode.trim() : '';
    let cleanCode = rawCode;
    const codeBlockMatch = cleanCode.match(/^```(?:html|javascript|js)?\s*\n([\s\S]*?)```$/);
    if (codeBlockMatch && codeBlockMatch[1]) {
      cleanCode = codeBlockMatch[1].trim();
    }
    // Auto-fix common Three.js method & constructor hallucinations generated by AI
    cleanCode = cleanCode
      .replace(/\.cubicBezierCurveTo\s*\(/g, '.bezierCurveTo(')
      .replace(/new\s+OrbitControls\s*\(/g, 'new (window.OrbitControls || (typeof THREE !== "undefined" && THREE.OrbitControls) || OrbitControls)(');
    const isFullHtml = /<!doctype/i.test(cleanCode) || /<html/i.test(cleanCode) || /<body/i.test(cleanCode);

    const htmlToUse = shape.props.isGltf && shape.props.gltfUrl
      ? `<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3D Model Preview</title>
    <style>
        body { 
            margin: 0; 
            padding: 0; 
            overflow: hidden; 
            width: 100%; 
            height: 100%;
            background-color: transparent;
        }
        canvas { 
            display: block; 
            width: 100% !important; 
            height: 100% !important;
        }
        /* Help tooltip */
        .help-tooltip {
            position: absolute;
            bottom: 10px;
            left: 10px;
            background: rgba(0,0,0,0.7);
            color: white;
            padding: 8px 12px;
            border-radius: 4px;
            font-family: sans-serif;
            font-size: 12px;
            opacity: 0.7;
            pointer-events: none;
        }
    </style>
</head>
<body>
    <div class="help-tooltip">
        <p>Left-click + drag: Rotate</p>
        <p>Right-click + drag: Pan</p>
        <p>Scroll: Zoom</p>
    </div>
    <script type="module">
    import * as THREE from "https://esm.sh/three";
    import { OrbitControls } from "https://esm.sh/three/examples/jsm/controls/OrbitControls.js";
    import { GLTFLoader } from "https://esm.sh/three/examples/jsm/loaders/GLTFLoader.js";
    
    // Set up scene
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0xf0f0f0);
    
    // Set up camera
    const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    camera.position.set(0, 0, 5);
    
    // Set up renderer
    const renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.shadowMap.enabled = true;
    document.body.appendChild(renderer.domElement);
    
    // Controls
    const controls = new OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    
    // Enhanced lighting setup
    // Ambient light for global illumination
    const ambientLight = new THREE.AmbientLight(0xffffff, 0.8);
    scene.add(ambientLight);
    
    // Main directional light (sun)
    const dirLight = new THREE.DirectionalLight(0xffffff, 1.2);
    dirLight.position.set(5, 10, 7);
    dirLight.castShadow = true;
    dirLight.shadow.mapSize.width = 1024;
    dirLight.shadow.mapSize.height = 1024;
    scene.add(dirLight);
    
    // Fill light from opposite direction
    const fillLight = new THREE.DirectionalLight(0x88bbff, 0.6);
    fillLight.position.set(-5, 0, -5);
    scene.add(fillLight);
    
    // Back light for rim lighting
    const backLight = new THREE.DirectionalLight(0xffeedd, 0.4);
    backLight.position.set(0, -5, -5);
    scene.add(backLight);
    
    // Load GLTF Model
    const loader = new GLTFLoader();
    loader.load(
      '${shape.props.gltfUrl}',
      (gltf) => {
        const model = gltf.scene;
        
        // Center and scale the model
        const box = new THREE.Box3().setFromObject(model);
        const center = box.getCenter(new THREE.Vector3());
        const size = box.getSize(new THREE.Vector3());
        
        // Reset position to center
        model.position.x = -center.x;
        model.position.y = -center.y;
        model.position.z = -center.z;
        
        // Scale to fit nicely in view
        const maxDim = Math.max(size.x, size.y, size.z);
        const scale = 3 / maxDim;
        model.scale.set(scale, scale, scale);
        
        // Enable shadows and enhance materials
        model.traverse((node) => {
          if (node.isMesh) {
            node.castShadow = true;
            node.receiveShadow = true;
            
            // If the material is basic, upgrade to standard for better lighting
            if (node.material) {
              // Ensure material reacts to light
              if (node.material.type === 'MeshBasicMaterial') {
                const prevMaterial = node.material;
                node.material = new THREE.MeshStandardMaterial({
                  color: prevMaterial.color,
                  map: prevMaterial.map,
                  roughness: 0.5,
                  metalness: 0.1
                });
              }
              // Adjust roughness for better appearance
              if ('roughness' in node.material) {
                node.material.roughness = 0.4;
              }
            }
          }
        });
        
        scene.add(model);
        
        // Adjust camera position based on model size
        camera.position.z = 5;
        controls.reset();
      },
      (xhr) => {
        console.log((xhr.loaded / xhr.total * 100) + '% loaded');
      },
      (error) => {
        console.error('An error happened loading the GLTF:', error);
      }
    );
    
    // Window resize handler
    window.addEventListener('resize', () => {
      camera.aspect = window.innerWidth / window.innerHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(window.innerWidth, window.innerHeight);
    });
    
    // Animation loop
    function animate() {
      requestAnimationFrame(animate);
      controls.update();
      renderer.render(scene, camera);
    }
    
    animate();
    
    // Prevent zooming issues
    window.addEventListener('wheel', e => { 
        if (!e.ctrlKey) return; 
        e.preventDefault(); 
    }, { passive: false });
    </script>
</body>
</html>`
      : cleanCode
        ? (() => {
            const htmlPolyfill = `
<script>
(function() {
  var _three = window.THREE;
  Object.defineProperty(window, 'OrbitControls', {
    get: function() {
      if (window.THREE && window.THREE.OrbitControls) return window.THREE.OrbitControls;
      return window.__OrbitControls;
    },
    set: function(v) {
      window.__OrbitControls = v;
      if (window.THREE) window.THREE.OrbitControls = v;
    },
    configurable: true
  });

  function patchThree(threeObj) {
    if (!threeObj) return;
    if (threeObj.OrbitControls && !window.__OrbitControls) {
      window.__OrbitControls = threeObj.OrbitControls;
    }
    if (threeObj.Shape && !threeObj.Shape.prototype.cubicBezierCurveTo) {
      threeObj.Shape.prototype.cubicBezierCurveTo = threeObj.Shape.prototype.bezierCurveTo;
    }
    if (threeObj.Path && !threeObj.Path.prototype.cubicBezierCurveTo) {
      threeObj.Path.prototype.cubicBezierCurveTo = threeObj.Path.prototype.bezierCurveTo;
    }
    if (threeObj.CurvePath && !threeObj.CurvePath.prototype.cubicBezierCurveTo) {
      threeObj.CurvePath.prototype.cubicBezierCurveTo = threeObj.CurvePath.prototype.bezierCurveTo;
    }
  }

  Object.defineProperty(window, 'THREE', {
    get: function() { return _three; },
    set: function(v) {
      _three = v;
      patchThree(v);
    },
    configurable: true
  });

  if (_three) patchThree(_three);
  window.addEventListener('DOMContentLoaded', function() { patchThree(window.THREE); });
  setInterval(function() { patchThree(window.THREE); }, 100);
})();
</script>
`;

            if (isFullHtml) {
              let finalHtml = cleanCode;
              if (/<head[^>]*>/i.test(finalHtml)) {
                return finalHtml.replace(/<head[^>]*>/i, `$&${htmlPolyfill}`);
              } else if (/<body[^>]*>/i.test(finalHtml)) {
                return finalHtml.replace(/<body[^>]*>/i, `$&${htmlPolyfill}`);
              }
              return htmlPolyfill + finalHtml;
            }

            return `<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3D Model Preview</title>
    <style>
        body { 
            margin: 0; 
            padding: 0; 
            overflow: hidden; 
            width: 100%; 
            height: 100%;
            background: radial-gradient(circle at center, #1e2038 0%, #0a0a14 100%);
            display: flex;
            align-items: center;
            justify-content: center;
        }
        canvas { 
            display: block; 
            width: 100% !important; 
            height: 100% !important;
        }
        .help-tooltip {
            position: absolute;
            bottom: 10px;
            left: 10px;
            background: rgba(15, 23, 42, 0.85);
            border: 1px solid rgba(255, 255, 255, 0.12);
            color: #cbd5e1;
            padding: 6px 10px;
            border-radius: 6px;
            font-family: system-ui, sans-serif;
            font-size: 11px;
            pointer-events: none;
            line-height: 1.5;
            backdrop-filter: blur(4px);
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js"></script>
</head>
<body>
    <div class="help-tooltip">
        <div>🖱️ Drag: Rotate</div>
        <div>🖱️ Right-click: Pan</div>
        <div>🖱️ Scroll: Zoom</div>
    </div>
    <script>
    // Ensure OrbitControls and Three curve methods are patched
    window.OrbitControls = THREE.OrbitControls;
    if (THREE.Shape && !THREE.Shape.prototype.cubicBezierCurveTo) {
      THREE.Shape.prototype.cubicBezierCurveTo = THREE.Shape.prototype.bezierCurveTo;
    }
    if (THREE.Path && !THREE.Path.prototype.cubicBezierCurveTo) {
      THREE.Path.prototype.cubicBezierCurveTo = THREE.Path.prototype.bezierCurveTo;
    }
    if (THREE.CurvePath && !THREE.CurvePath.prototype.cubicBezierCurveTo) {
      THREE.CurvePath.prototype.cubicBezierCurveTo = THREE.CurvePath.prototype.bezierCurveTo;
    }

    const rawSnippet = ${JSON.stringify(cleanCode)};
    const hasOwnRenderer = /new\\s+THREE\\.WebGLRenderer/i.test(rawSnippet) || /document\\.body\\.appendChild/i.test(rawSnippet);

    if (hasOwnRenderer) {
      try {
        const scriptFn = new Function('THREE', 'OrbitControls', rawSnippet);
        scriptFn(THREE, THREE.OrbitControls);
      } catch (err) {
        console.error("Custom script execution error:", err);
      }
    } else {
      const scene = new THREE.Scene();
      const camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 1000);
      camera.position.set(0, 1.5, 4);

      const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
      renderer.setSize(window.innerWidth, window.innerHeight);
      renderer.setPixelRatio(window.devicePixelRatio);
      renderer.shadowMap.enabled = true;
      if (THREE.ACESFilmicToneMapping) {
        renderer.toneMapping = THREE.ACESFilmicToneMapping;
        renderer.toneMappingExposure = 1.2;
      }
      document.body.appendChild(renderer.domElement);

      const controls = new THREE.OrbitControls(camera, renderer.domElement);
      controls.enableDamping = true;
      controls.dampingFactor = 0.05;
      controls.autoRotate = true;
      controls.autoRotateSpeed = 1.5;

      // Studio Lighting
      const ambientLight = new THREE.AmbientLight(0xffffff, 0.85);
      scene.add(ambientLight);

      const keyLight = new THREE.DirectionalLight(0xffffff, 1.5);
      keyLight.position.set(5, 8, 5);
      keyLight.castShadow = true;
      scene.add(keyLight);

      const fillLight = new THREE.DirectionalLight(0x88bbff, 0.7);
      fillLight.position.set(-5, 3, -3);
      scene.add(fillLight);

      const rimLight = new THREE.DirectionalLight(0xffaa66, 0.5);
      rimLight.position.set(0, -4, -4);
      scene.add(rimLight);

      const modelGroup = new THREE.Group();
      scene.add(modelGroup);

      let returnedObject = null;
      try {
        const userFn = new Function('THREE', 'scene', 'camera', 'renderer', 'controls', 'modelGroup', rawSnippet);
        returnedObject = userFn(THREE, scene, camera, renderer, controls, modelGroup);
      } catch (e1) {
        console.warn("Function execution warning, trying eval fallback:", e1);
        try {
          eval(rawSnippet);
        } catch (e2) {
          console.error("Eval error:", e2);
        }
      }

      if (returnedObject && returnedObject instanceof THREE.Object3D) {
        if (returnedObject !== modelGroup && !modelGroup.children.includes(returnedObject)) {
          scene.add(returnedObject);
        }
      }

      // Auto-fit camera to model
      try {
        const targetBox = new THREE.Box3().setFromObject(scene);
        if (!targetBox.isEmpty()) {
          const center = targetBox.getCenter(new THREE.Vector3());
          const size = targetBox.getSize(new THREE.Vector3());
          const maxDim = Math.max(size.x, size.y, size.z);
          if (maxDim > 0 && maxDim !== Infinity) {
            controls.target.copy(center);
            camera.position.set(center.x, center.y + maxDim * 0.4, center.z + maxDim * 2.2);
            controls.update();
          }
        }
      } catch (boxErr) {
        console.warn("Box framing error:", boxErr);
      }

      function animate() {
        requestAnimationFrame(animate);
        controls.update();
        renderer.render(scene, camera);
      }
      animate();

      window.addEventListener('resize', () => {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(window.innerWidth, window.innerHeight);
      });
    }

    window.addEventListener('wheel', e => { 
        if (!e.ctrlKey) return; 
        e.preventDefault(); 
    }, { passive: false });
    </script>
</body>
</html>`;
          })()
        : ''

    const handlePushTo3DWorld = async () => {
      if (shape.props.isGltf && shape.props.gltfUrl) {
        const obj = await addObjectWithGltf(shape.props.gltfUrl);
        if (obj) {
          obj.userData.tldrawShapeId = shape.id;
          if (!(window as any).__shapeToObjectMap) {
            (window as any).__shapeToObjectMap = new Map();
          }
          (window as any).__shapeToObjectMap.set(shape.id, obj.uuid);
          toast.addToast({ icon: 'check', title: 'Added to 3D World! Open 3D World tab to explore.' });
        } else {
          toast.addToast({ icon: 'warning-triangle', title: 'Failed to add 3D model.' });
        }
      } else if (shape.props.threeJsCode) {
        try {
          const res = await fetch("http://localhost:8000/api/cerebras/parse", {
            method: "POST",
            body: shape.props.threeJsCode
          });
          const actualCode = await res.json();
          const objectCode = actualCode.content;

          const obj = addObjectFromCode(objectCode);
          if (obj) {
            obj.userData.tldrawShapeId = shape.id;
            if (!(window as any).__shapeToObjectMap) {
              (window as any).__shapeToObjectMap = new Map();
            }
            (window as any).__shapeToObjectMap.set(shape.id, obj.uuid);
            toast.addToast({ icon: 'check', title: 'Added to 3D World! Open 3D World tab to explore.' });
          } else {
            toast.addToast({ icon: 'warning-triangle', title: 'Failed to add object.' });
          }
        } catch (err) {
          toast.addToast({ icon: 'warning-triangle', title: 'Error adding to 3D World.' });
        }
      }
    };

    const handleRemoveFrom3DWorld = () => {
      try {
        const objectStore = useObjectStore.getState();
        const map = (window as any).__shapeToObjectMap;
        const mappedId = map ? map.get(shape.id) : null;
        const targetObj = objectStore.objects.find(
          o => o.id === shape.props.objectId || o.id === mappedId || (o as any).uuid === mappedId || o.userData?.tldrawShapeId === shape.id
        );
        if (targetObj) {
          objectStore.removeObject(targetObj.id);
          toast.addToast({ icon: 'check', title: 'Removed object from 3D World!' });
        } else if (shape.props.objectId) {
          objectStore.removeObject(shape.props.objectId);
          toast.addToast({ icon: 'check', title: 'Removed object from 3D World!' });
        } else if (mappedId) {
          objectStore.removeObject(mappedId);
          toast.addToast({ icon: 'check', title: 'Removed object from 3D World!' });
        } else {
          toast.addToast({ icon: 'warning-triangle', title: 'Object is not in 3D World.' });
        }
        if (map) map.delete(shape.id);
      } catch (err) {
        console.error("Error removing from 3D World:", err);
      }
    };


    return (
      <HTMLContainer className="tl-embed-container" id={shape.id}>
        {htmlToUse ? (
          <>
            <iframe
              id={`iframe-1-${shape.id}`}
              srcDoc={htmlToUse}
              width={toDomPrecision(shape.props.w)}
              height={toDomPrecision(shape.props.h)}
              draggable={false}
              style={{
                pointerEvents: isEditing ? 'auto' : 'none',
                border: '1px solid var(--color-panel-contrast)',
                borderRadius: 'var(--radius-2)',
                backgroundColor: 'rgba(0,0,0,0.1)',
              }}
            />
            {(isRegenerating || isEditingModel) && (
              <div
                style={{
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  width: '100%',
                  height: '100%',
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'center',
                  backgroundColor: 'rgba(0,0,0,0.7)',
                  color: 'white',
                  borderRadius: 'var(--radius-2)',
                  zIndex: 100,
                }}
              >
                <DefaultSpinner />
                <div style={{ marginTop: 10, fontSize: 14 }}>
                  {isRegenerating ? 'Regenerating 3D model...' : 'Editing 3D model...'}
                </div>
              </div>
            )}
          </>
        ) : (
          <div
            style={{
              width: '100%',
              height: '100%',
              backgroundColor: 'var(--color-muted-2)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              border: '1px solid var(--color-muted-1)',
            }}
          >
            <DefaultSpinner />
          </div>
        )}
        <div
          style={{
            position: 'absolute',
            top: 15,
            right: -40,
            height: 40,
            width: 40,
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'left',
            justifyContent: 'center',
            cursor: 'pointer',
            pointerEvents: 'all',
            paddingLeft: 5,
            paddingTop: 5,
            gap: 5
          }}
        >
          <Icon
            icon="duplicate"
            onTouchStart={() => {
              if (navigator && navigator.clipboard) {
                navigator.clipboard.writeText(shape.props.threeJsCode)
                toast.addToast({
                  icon: 'duplicate',
                  title: 'Model code copied to clipboard',
                })
              }
            }}
            onClick={() => {
              if (navigator && navigator.clipboard) {
                navigator.clipboard.writeText(shape.props.threeJsCode)
                toast.addToast({
                  icon: 'duplicate',
                  title: 'Model code copied to clipboard',
                })
              }
            }}
            onPointerDown={(e) => e.stopPropagation()}
          />
          <Icon
            icon="redo"
            onTouchStart={async () => {
              setIsRegenerating(true);
              this.editor.setSelectedShapes(shape.props.selectedShapes);
              await vibe3DCode(this.editor, shape.id);
              setIsRegenerating(false);
              // Exit editing mode after regenerating the 3D preview
              this.editor.selectNone();
            }}
            onClick={async () => {
              setIsRegenerating(true);
              this.editor.setSelectedShapes(shape.props.selectedShapes);
              await vibe3DCode(this.editor, shape.id);
              setIsRegenerating(false);
              // Exit editing mode after regenerating the 3D preview
              this.editor.selectNone();
            }}
            onPointerDown={(e) => e.stopPropagation()}
          />
          <Icon
            icon="plus"
            onTouchStart={handlePushTo3DWorld}
            onClick={handlePushTo3DWorld}
            onPointerDown={(e) => e.stopPropagation()}
          />
          <Icon
            icon="trash"
            onTouchStart={handleRemoveFrom3DWorld}
            onClick={handleRemoveFrom3DWorld}
            onPointerDown={(e) => e.stopPropagation()}
          />
        </div>
        {htmlToUse && (
          <div
            style={{
              textAlign: 'center',
              position: 'absolute',
              bottom: isEditing ? -40 : 0,
              padding: 4,
              fontFamily: 'inherit',
              fontSize: 12,
              left: 0,
              width: '100%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              pointerEvents: 'none',
            }}
          >
            <span
              style={{
                background: 'var(--color-panel)',
                padding: '4px 12px',
                borderRadius: 99,
                border: '1px solid var(--color-muted-1)',
              }}
            >
              {isEditing ? 'Click the canvas to exit' : 'Double click to interact with 3D model'}
            </span>
          </div>
        )}
      </HTMLContainer>
    )
  }

  override toSvg(
    shape: Model3DPreviewShape,
    _ctx: SvgExportContext
  ): SVGElement | Promise<SVGElement> {
    const g = document.createElementNS('http://www.w3.org/2000/svg', 'g')

    return new Promise((resolve, _) => {
      if (window === undefined) return resolve(g)

      const windowListener = (event: MessageEvent) => {
        if (event.data.screenshot && event.data?.shapeid === shape.id) {
          const image = document.createElementNS('http://www.w3.org/2000/svg', 'image')
          image.setAttributeNS('http://www.w3.org/1999/xlink', 'href', event.data.screenshot)
          image.setAttribute('width', shape.props.w.toString())
          image.setAttribute('height', shape.props.h.toString())
          g.appendChild(image)
          window.removeEventListener('message', windowListener)
          clearTimeout(timeOut)
          resolve(g)
        }
      }

      const timeOut = setTimeout(() => {
        resolve(g)
        window.removeEventListener('message', windowListener)
      }, 2000)

      window.addEventListener('message', windowListener)

      // Request a screenshot from the iframe
      const firstLevelIframe = document.getElementById(`iframe-1-${shape.id}`) as HTMLIFrameElement
      if (firstLevelIframe) {
        firstLevelIframe.contentWindow!.postMessage(
          { action: 'take-screenshot', shapeid: shape.id },
          '*'
        )
      } else {
        console.log('first level iframe not found or not accessible')
      }
    })
  }

  indicator(shape: Model3DPreviewShape) {
    return <rect width={shape.props.w} height={shape.props.h} />
  }
}
